/* Automatically @generated by tree-sitter */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 48
#define LARGE_STATE_COUNT 11
#define SYMBOL_COUNT 49
#define ALIAS_COUNT 0
#define TOKEN_COUNT 33
#define EXTERNAL_TOKEN_COUNT 1
#define FIELD_COUNT 1
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 6
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym__newline = 2,
  aux_sym_line_comment_token1 = 3,
  aux_sym_line_comment_token2 = 4,
  anon_sym_STAR = 5,
  aux_sym_line_comment_token3 = 6,
  sym_block_comment = 7,
  anon_sym_program = 8,
  anon_sym_define = 9,
  anon_sym_end = 10,
  anon_sym_mata = 11,
  anon_sym_COLON = 12,
  aux_sym__mata_line_token1 = 13,
  anon_sym_local = 14,
  anon_sym_loc = 15,
  anon_sym_global = 16,
  anon_sym_gl = 17,
  anon_sym_tempvar = 18,
  anon_sym_tempname = 19,
  anon_sym_tempfile = 20,
  anon_sym_by = 21,
  anon_sym_bysort = 22,
  anon_sym_bys = 23,
  anon_sym_quietly = 24,
  anon_sym_qui = 25,
  anon_sym_noisily = 26,
  anon_sym_noi = 27,
  anon_sym_capture = 28,
  anon_sym_cap = 29,
  anon_sym_sortpreserve = 30,
  sym__rest_of_line = 31,
  sym__line_start = 32,
  sym_source_file = 33,
  sym__line = 34,
  sym__statement = 35,
  sym_comment = 36,
  sym_line_comment = 37,
  sym_program_definition = 38,
  sym__program_line = 39,
  sym_mata_block = 40,
  sym__mata_line = 41,
  sym_macro_definition = 42,
  sym_command = 43,
  sym_prefix = 44,
  aux_sym_source_file_repeat1 = 45,
  aux_sym_program_definition_repeat1 = 46,
  aux_sym_mata_block_repeat1 = 47,
  aux_sym_macro_definition_repeat1 = 48,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym__newline] = "_newline",
  [aux_sym_line_comment_token1] = "line_comment_token1",
  [aux_sym_line_comment_token2] = "line_comment_token2",
  [anon_sym_STAR] = "*",
  [aux_sym_line_comment_token3] = "line_comment_token3",
  [sym_block_comment] = "block_comment",
  [anon_sym_program] = "program",
  [anon_sym_define] = "define",
  [anon_sym_end] = "end",
  [anon_sym_mata] = "mata",
  [anon_sym_COLON] = ":",
  [aux_sym__mata_line_token1] = "_mata_line_token1",
  [anon_sym_local] = "local",
  [anon_sym_loc] = "loc",
  [anon_sym_global] = "global",
  [anon_sym_gl] = "gl",
  [anon_sym_tempvar] = "tempvar",
  [anon_sym_tempname] = "tempname",
  [anon_sym_tempfile] = "tempfile",
  [anon_sym_by] = "by",
  [anon_sym_bysort] = "bysort",
  [anon_sym_bys] = "bys",
  [anon_sym_quietly] = "quietly",
  [anon_sym_qui] = "qui",
  [anon_sym_noisily] = "noisily",
  [anon_sym_noi] = "noi",
  [anon_sym_capture] = "capture",
  [anon_sym_cap] = "cap",
  [anon_sym_sortpreserve] = "sortpreserve",
  [sym__rest_of_line] = "_rest_of_line",
  [sym__line_start] = "_line_start",
  [sym_source_file] = "source_file",
  [sym__line] = "_line",
  [sym__statement] = "_statement",
  [sym_comment] = "comment",
  [sym_line_comment] = "line_comment",
  [sym_program_definition] = "program_definition",
  [sym__program_line] = "_program_line",
  [sym_mata_block] = "mata_block",
  [sym__mata_line] = "_mata_line",
  [sym_macro_definition] = "macro_definition",
  [sym_command] = "command",
  [sym_prefix] = "prefix",
  [aux_sym_source_file_repeat1] = "source_file_repeat1",
  [aux_sym_program_definition_repeat1] = "program_definition_repeat1",
  [aux_sym_mata_block_repeat1] = "mata_block_repeat1",
  [aux_sym_macro_definition_repeat1] = "macro_definition_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym__newline] = sym__newline,
  [aux_sym_line_comment_token1] = aux_sym_line_comment_token1,
  [aux_sym_line_comment_token2] = aux_sym_line_comment_token2,
  [anon_sym_STAR] = anon_sym_STAR,
  [aux_sym_line_comment_token3] = aux_sym_line_comment_token3,
  [sym_block_comment] = sym_block_comment,
  [anon_sym_program] = anon_sym_program,
  [anon_sym_define] = anon_sym_define,
  [anon_sym_end] = anon_sym_end,
  [anon_sym_mata] = anon_sym_mata,
  [anon_sym_COLON] = anon_sym_COLON,
  [aux_sym__mata_line_token1] = aux_sym__mata_line_token1,
  [anon_sym_local] = anon_sym_local,
  [anon_sym_loc] = anon_sym_loc,
  [anon_sym_global] = anon_sym_global,
  [anon_sym_gl] = anon_sym_gl,
  [anon_sym_tempvar] = anon_sym_tempvar,
  [anon_sym_tempname] = anon_sym_tempname,
  [anon_sym_tempfile] = anon_sym_tempfile,
  [anon_sym_by] = anon_sym_by,
  [anon_sym_bysort] = anon_sym_bysort,
  [anon_sym_bys] = anon_sym_bys,
  [anon_sym_quietly] = anon_sym_quietly,
  [anon_sym_qui] = anon_sym_qui,
  [anon_sym_noisily] = anon_sym_noisily,
  [anon_sym_noi] = anon_sym_noi,
  [anon_sym_capture] = anon_sym_capture,
  [anon_sym_cap] = anon_sym_cap,
  [anon_sym_sortpreserve] = anon_sym_sortpreserve,
  [sym__rest_of_line] = sym__rest_of_line,
  [sym__line_start] = sym__line_start,
  [sym_source_file] = sym_source_file,
  [sym__line] = sym__line,
  [sym__statement] = sym__statement,
  [sym_comment] = sym_comment,
  [sym_line_comment] = sym_line_comment,
  [sym_program_definition] = sym_program_definition,
  [sym__program_line] = sym__program_line,
  [sym_mata_block] = sym_mata_block,
  [sym__mata_line] = sym__mata_line,
  [sym_macro_definition] = sym_macro_definition,
  [sym_command] = sym_command,
  [sym_prefix] = sym_prefix,
  [aux_sym_source_file_repeat1] = aux_sym_source_file_repeat1,
  [aux_sym_program_definition_repeat1] = aux_sym_program_definition_repeat1,
  [aux_sym_mata_block_repeat1] = aux_sym_mata_block_repeat1,
  [aux_sym_macro_definition_repeat1] = aux_sym_macro_definition_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym__newline] = {
    .visible = false,
    .named = true,
  },
  [aux_sym_line_comment_token1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_line_comment_token2] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_STAR] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_line_comment_token3] = {
    .visible = false,
    .named = false,
  },
  [sym_block_comment] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_program] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_define] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_end] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_mata] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_COLON] = {
    .visible = true,
    .named = false,
  },
  [aux_sym__mata_line_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_local] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_loc] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_global] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_gl] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tempvar] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tempname] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_tempfile] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_by] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bysort] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_bys] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_quietly] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_qui] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_noisily] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_noi] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_capture] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_cap] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_sortpreserve] = {
    .visible = true,
    .named = false,
  },
  [sym__rest_of_line] = {
    .visible = false,
    .named = true,
  },
  [sym__line_start] = {
    .visible = false,
    .named = true,
  },
  [sym_source_file] = {
    .visible = true,
    .named = true,
  },
  [sym__line] = {
    .visible = false,
    .named = true,
  },
  [sym__statement] = {
    .visible = false,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_line_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_program_definition] = {
    .visible = true,
    .named = true,
  },
  [sym__program_line] = {
    .visible = false,
    .named = true,
  },
  [sym_mata_block] = {
    .visible = true,
    .named = true,
  },
  [sym__mata_line] = {
    .visible = false,
    .named = true,
  },
  [sym_macro_definition] = {
    .visible = true,
    .named = true,
  },
  [sym_command] = {
    .visible = true,
    .named = true,
  },
  [sym_prefix] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_source_file_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_program_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_mata_block_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_macro_definition_repeat1] = {
    .visible = false,
    .named = false,
  },
};

enum ts_field_identifiers {
  field_name = 1,
};

static const char * const ts_field_names[] = {
  [0] = NULL,
  [field_name] = "name",
};

static const TSMapSlice ts_field_map_slices[PRODUCTION_ID_COUNT] = {
  [1] = {.index = 0, .length = 1},
  [2] = {.index = 1, .length = 1},
  [3] = {.index = 2, .length = 1},
  [4] = {.index = 3, .length = 2},
  [5] = {.index = 5, .length = 1},
};

static const TSFieldMapEntry ts_field_map_entries[] = {
  [0] =
    {field_name, 0},
  [1] =
    {field_name, 1},
  [2] =
    {field_name, 1, .inherited = true},
  [3] =
    {field_name, 0, .inherited = true},
    {field_name, 1, .inherited = true},
  [5] =
    {field_name, 2},
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 13,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 19,
  [20] = 20,
  [21] = 21,
  [22] = 22,
  [23] = 23,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '*') ADVANCE(11);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == ':') ADVANCE(17);
      if (lookahead == 'e') ADVANCE(27);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 1:
      if (lookahead == '\n') ADVANCE(8);
      END_STATE();
    case 2:
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 3:
      if (lookahead == '*') ADVANCE(5);
      if (lookahead == '/') ADVANCE(9);
      END_STATE();
    case 4:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead == '/') ADVANCE(14);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 5:
      if (lookahead == '*') ADVANCE(4);
      if (lookahead != 0) ADVANCE(5);
      END_STATE();
    case 6:
      if (eof) ADVANCE(7);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '/') ADVANCE(3);
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(6);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 7:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 8:
      ACCEPT_TOKEN(sym__newline);
      END_STATE();
    case 9:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead == '/') ADVANCE(10);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 10:
      ACCEPT_TOKEN(aux_sym_line_comment_token1);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(10);
      END_STATE();
    case 11:
      ACCEPT_TOKEN(anon_sym_STAR);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(aux_sym_line_comment_token3);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(12);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(13);
      END_STATE();
    case 13:
      ACCEPT_TOKEN(aux_sym_line_comment_token3);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(13);
      END_STATE();
    case 14:
      ACCEPT_TOKEN(sym_block_comment);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_end);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 16:
      ACCEPT_TOKEN(anon_sym_end);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 17:
      ACCEPT_TOKEN(anon_sym_COLON);
      END_STATE();
    case 18:
      ACCEPT_TOKEN(anon_sym_COLON);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 19:
      ACCEPT_TOKEN(aux_sym__mata_line_token1);
      if (lookahead == ':') ADVANCE(18);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(19);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 20:
      ACCEPT_TOKEN(aux_sym__mata_line_token1);
      if (lookahead == 'd') ADVANCE(16);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 21:
      ACCEPT_TOKEN(aux_sym__mata_line_token1);
      if (lookahead == 'e') ADVANCE(22);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(21);
      if (lookahead != 0 &&
          lookahead != '\t' &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 22:
      ACCEPT_TOKEN(aux_sym__mata_line_token1);
      if (lookahead == 'n') ADVANCE(20);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(aux_sym__mata_line_token1);
      if (lookahead != 0 &&
          lookahead != '\n') ADVANCE(23);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(sym__rest_of_line);
      if (lookahead == '\n') ADVANCE(8);
      if (lookahead == '\r') ADVANCE(1);
      if (lookahead == '\t' ||
          lookahead == ' ') ADVANCE(24);
      if (lookahead != 0) ADVANCE(25);
      END_STATE();
    case 25:
      ACCEPT_TOKEN(sym__rest_of_line);
      if (lookahead != 0 &&
          lookahead != '\n' &&
          lookahead != '\r') ADVANCE(25);
      END_STATE();
    case 26:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'd') ADVANCE(15);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(sym_identifier);
      if (lookahead == 'n') ADVANCE(26);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    case 28:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(28);
      END_STATE();
    default:
      return false;
  }
}

static bool ts_lex_keywords(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      ADVANCE_MAP(
        'b', 1,
        'c', 2,
        'd', 3,
        'g', 4,
        'l', 5,
        'm', 6,
        'n', 7,
        'p', 8,
        'q', 9,
        's', 10,
        't', 11,
      );
      if (lookahead == '\t' ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == 'y') ADVANCE(12);
      END_STATE();
    case 2:
      if (lookahead == 'a') ADVANCE(13);
      END_STATE();
    case 3:
      if (lookahead == 'e') ADVANCE(14);
      END_STATE();
    case 4:
      if (lookahead == 'l') ADVANCE(15);
      END_STATE();
    case 5:
      if (lookahead == 'o') ADVANCE(16);
      END_STATE();
    case 6:
      if (lookahead == 'a') ADVANCE(17);
      END_STATE();
    case 7:
      if (lookahead == 'o') ADVANCE(18);
      END_STATE();
    case 8:
      if (lookahead == 'r') ADVANCE(19);
      END_STATE();
    case 9:
      if (lookahead == 'u') ADVANCE(20);
      END_STATE();
    case 10:
      if (lookahead == 'o') ADVANCE(21);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(22);
      END_STATE();
    case 12:
      ACCEPT_TOKEN(anon_sym_by);
      if (lookahead == 's') ADVANCE(23);
      END_STATE();
    case 13:
      if (lookahead == 'p') ADVANCE(24);
      END_STATE();
    case 14:
      if (lookahead == 'f') ADVANCE(25);
      END_STATE();
    case 15:
      ACCEPT_TOKEN(anon_sym_gl);
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 16:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 17:
      if (lookahead == 't') ADVANCE(28);
      END_STATE();
    case 18:
      if (lookahead == 'i') ADVANCE(29);
      END_STATE();
    case 19:
      if (lookahead == 'o') ADVANCE(30);
      END_STATE();
    case 20:
      if (lookahead == 'i') ADVANCE(31);
      END_STATE();
    case 21:
      if (lookahead == 'r') ADVANCE(32);
      END_STATE();
    case 22:
      if (lookahead == 'm') ADVANCE(33);
      END_STATE();
    case 23:
      ACCEPT_TOKEN(anon_sym_bys);
      if (lookahead == 'o') ADVANCE(34);
      END_STATE();
    case 24:
      ACCEPT_TOKEN(anon_sym_cap);
      if (lookahead == 't') ADVANCE(35);
      END_STATE();
    case 25:
      if (lookahead == 'i') ADVANCE(36);
      END_STATE();
    case 26:
      if (lookahead == 'b') ADVANCE(37);
      END_STATE();
    case 27:
      ACCEPT_TOKEN(anon_sym_loc);
      if (lookahead == 'a') ADVANCE(38);
      END_STATE();
    case 28:
      if (lookahead == 'a') ADVANCE(39);
      END_STATE();
    case 29:
      ACCEPT_TOKEN(anon_sym_noi);
      if (lookahead == 's') ADVANCE(40);
      END_STATE();
    case 30:
      if (lookahead == 'g') ADVANCE(41);
      END_STATE();
    case 31:
      ACCEPT_TOKEN(anon_sym_qui);
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 32:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 33:
      if (lookahead == 'p') ADVANCE(44);
      END_STATE();
    case 34:
      if (lookahead == 'r') ADVANCE(45);
      END_STATE();
    case 35:
      if (lookahead == 'u') ADVANCE(46);
      END_STATE();
    case 36:
      if (lookahead == 'n') ADVANCE(47);
      END_STATE();
    case 37:
      if (lookahead == 'a') ADVANCE(48);
      END_STATE();
    case 38:
      if (lookahead == 'l') ADVANCE(49);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(anon_sym_mata);
      END_STATE();
    case 40:
      if (lookahead == 'i') ADVANCE(50);
      END_STATE();
    case 41:
      if (lookahead == 'r') ADVANCE(51);
      END_STATE();
    case 42:
      if (lookahead == 't') ADVANCE(52);
      END_STATE();
    case 43:
      if (lookahead == 'p') ADVANCE(53);
      END_STATE();
    case 44:
      if (lookahead == 'f') ADVANCE(54);
      if (lookahead == 'n') ADVANCE(55);
      if (lookahead == 'v') ADVANCE(56);
      END_STATE();
    case 45:
      if (lookahead == 't') ADVANCE(57);
      END_STATE();
    case 46:
      if (lookahead == 'r') ADVANCE(58);
      END_STATE();
    case 47:
      if (lookahead == 'e') ADVANCE(59);
      END_STATE();
    case 48:
      if (lookahead == 'l') ADVANCE(60);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(anon_sym_local);
      END_STATE();
    case 50:
      if (lookahead == 'l') ADVANCE(61);
      END_STATE();
    case 51:
      if (lookahead == 'a') ADVANCE(62);
      END_STATE();
    case 52:
      if (lookahead == 'l') ADVANCE(63);
      END_STATE();
    case 53:
      if (lookahead == 'r') ADVANCE(64);
      END_STATE();
    case 54:
      if (lookahead == 'i') ADVANCE(65);
      END_STATE();
    case 55:
      if (lookahead == 'a') ADVANCE(66);
      END_STATE();
    case 56:
      if (lookahead == 'a') ADVANCE(67);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(anon_sym_bysort);
      END_STATE();
    case 58:
      if (lookahead == 'e') ADVANCE(68);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_define);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_global);
      END_STATE();
    case 61:
      if (lookahead == 'y') ADVANCE(69);
      END_STATE();
    case 62:
      if (lookahead == 'm') ADVANCE(70);
      END_STATE();
    case 63:
      if (lookahead == 'y') ADVANCE(71);
      END_STATE();
    case 64:
      if (lookahead == 'e') ADVANCE(72);
      END_STATE();
    case 65:
      if (lookahead == 'l') ADVANCE(73);
      END_STATE();
    case 66:
      if (lookahead == 'm') ADVANCE(74);
      END_STATE();
    case 67:
      if (lookahead == 'r') ADVANCE(75);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_capture);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_noisily);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_program);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_quietly);
      END_STATE();
    case 72:
      if (lookahead == 's') ADVANCE(76);
      END_STATE();
    case 73:
      if (lookahead == 'e') ADVANCE(77);
      END_STATE();
    case 74:
      if (lookahead == 'e') ADVANCE(78);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(anon_sym_tempvar);
      END_STATE();
    case 76:
      if (lookahead == 'e') ADVANCE(79);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(anon_sym_tempfile);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(anon_sym_tempname);
      END_STATE();
    case 79:
      if (lookahead == 'r') ADVANCE(80);
      END_STATE();
    case 80:
      if (lookahead == 'v') ADVANCE(81);
      END_STATE();
    case 81:
      if (lookahead == 'e') ADVANCE(82);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(anon_sym_sortpreserve);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 6, .external_lex_state = 1},
  [2] = {.lex_state = 0, .external_lex_state = 1},
  [3] = {.lex_state = 0, .external_lex_state = 1},
  [4] = {.lex_state = 0, .external_lex_state = 1},
  [5] = {.lex_state = 6, .external_lex_state = 1},
  [6] = {.lex_state = 6, .external_lex_state = 1},
  [7] = {.lex_state = 0, .external_lex_state = 1},
  [8] = {.lex_state = 0, .external_lex_state = 1},
  [9] = {.lex_state = 6, .external_lex_state = 1},
  [10] = {.lex_state = 0, .external_lex_state = 1},
  [11] = {.lex_state = 19},
  [12] = {.lex_state = 21},
  [13] = {.lex_state = 21},
  [14] = {.lex_state = 21},
  [15] = {.lex_state = 21},
  [16] = {.lex_state = 6},
  [17] = {.lex_state = 6},
  [18] = {.lex_state = 6},
  [19] = {.lex_state = 6},
  [20] = {.lex_state = 2},
  [21] = {.lex_state = 2},
  [22] = {.lex_state = 6},
  [23] = {.lex_state = 2},
  [24] = {.lex_state = 21},
  [25] = {.lex_state = 0},
  [26] = {.lex_state = 0},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 0},
  [29] = {.lex_state = 0},
  [30] = {.lex_state = 0},
  [31] = {.lex_state = 0},
  [32] = {.lex_state = 0},
  [33] = {.lex_state = 0},
  [34] = {.lex_state = 0},
  [35] = {.lex_state = 0},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 0},
  [39] = {.lex_state = 12},
  [40] = {.lex_state = 0},
  [41] = {.lex_state = 0},
  [42] = {.lex_state = 0},
  [43] = {.lex_state = 0},
  [44] = {.lex_state = 0},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 0},
  [47] = {.lex_state = 0},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [sym_identifier] = ACTIONS(1),
    [sym__newline] = ACTIONS(1),
    [aux_sym_line_comment_token1] = ACTIONS(1),
    [aux_sym_line_comment_token2] = ACTIONS(1),
    [anon_sym_STAR] = ACTIONS(1),
    [sym_block_comment] = ACTIONS(1),
    [anon_sym_program] = ACTIONS(1),
    [anon_sym_define] = ACTIONS(1),
    [anon_sym_end] = ACTIONS(1),
    [anon_sym_mata] = ACTIONS(1),
    [anon_sym_COLON] = ACTIONS(1),
    [anon_sym_local] = ACTIONS(1),
    [anon_sym_loc] = ACTIONS(1),
    [anon_sym_global] = ACTIONS(1),
    [anon_sym_gl] = ACTIONS(1),
    [anon_sym_tempvar] = ACTIONS(1),
    [anon_sym_tempname] = ACTIONS(1),
    [anon_sym_tempfile] = ACTIONS(1),
    [anon_sym_by] = ACTIONS(1),
    [anon_sym_bysort] = ACTIONS(1),
    [anon_sym_bys] = ACTIONS(1),
    [anon_sym_quietly] = ACTIONS(1),
    [anon_sym_qui] = ACTIONS(1),
    [anon_sym_noisily] = ACTIONS(1),
    [anon_sym_noi] = ACTIONS(1),
    [anon_sym_capture] = ACTIONS(1),
    [anon_sym_cap] = ACTIONS(1),
    [anon_sym_sortpreserve] = ACTIONS(1),
    [sym__line_start] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_source_file] = STATE(30),
    [sym__line] = STATE(5),
    [sym__statement] = STATE(35),
    [sym_comment] = STATE(35),
    [sym_line_comment] = STATE(26),
    [sym_program_definition] = STATE(35),
    [sym_mata_block] = STATE(35),
    [sym_macro_definition] = STATE(35),
    [sym_command] = STATE(35),
    [sym_prefix] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(5),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(7),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(2)] = {
    [sym__statement] = STATE(32),
    [sym_comment] = STATE(32),
    [sym_line_comment] = STATE(26),
    [sym_program_definition] = STATE(32),
    [sym__program_line] = STATE(3),
    [sym_mata_block] = STATE(32),
    [sym_macro_definition] = STATE(32),
    [sym_command] = STATE(32),
    [sym_prefix] = STATE(36),
    [aux_sym_program_definition_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(27),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_end] = ACTIONS(29),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(3)] = {
    [sym__statement] = STATE(32),
    [sym_comment] = STATE(32),
    [sym_line_comment] = STATE(26),
    [sym_program_definition] = STATE(32),
    [sym__program_line] = STATE(3),
    [sym_mata_block] = STATE(32),
    [sym_macro_definition] = STATE(32),
    [sym_command] = STATE(32),
    [sym_prefix] = STATE(36),
    [aux_sym_program_definition_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(31),
    [sym__newline] = ACTIONS(34),
    [aux_sym_line_comment_token1] = ACTIONS(37),
    [aux_sym_line_comment_token2] = ACTIONS(40),
    [sym_block_comment] = ACTIONS(43),
    [anon_sym_program] = ACTIONS(46),
    [anon_sym_end] = ACTIONS(49),
    [anon_sym_mata] = ACTIONS(51),
    [anon_sym_local] = ACTIONS(54),
    [anon_sym_loc] = ACTIONS(54),
    [anon_sym_global] = ACTIONS(54),
    [anon_sym_gl] = ACTIONS(54),
    [anon_sym_tempvar] = ACTIONS(57),
    [anon_sym_tempname] = ACTIONS(57),
    [anon_sym_tempfile] = ACTIONS(57),
    [anon_sym_by] = ACTIONS(60),
    [anon_sym_bysort] = ACTIONS(60),
    [anon_sym_bys] = ACTIONS(60),
    [anon_sym_quietly] = ACTIONS(60),
    [anon_sym_qui] = ACTIONS(60),
    [anon_sym_noisily] = ACTIONS(60),
    [anon_sym_noi] = ACTIONS(60),
    [anon_sym_capture] = ACTIONS(60),
    [anon_sym_cap] = ACTIONS(60),
    [anon_sym_sortpreserve] = ACTIONS(60),
    [sym__line_start] = ACTIONS(63),
  },
  [STATE(4)] = {
    [sym__statement] = STATE(32),
    [sym_comment] = STATE(32),
    [sym_line_comment] = STATE(26),
    [sym_program_definition] = STATE(32),
    [sym__program_line] = STATE(8),
    [sym_mata_block] = STATE(32),
    [sym_macro_definition] = STATE(32),
    [sym_command] = STATE(32),
    [sym_prefix] = STATE(36),
    [aux_sym_program_definition_repeat1] = STATE(8),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(66),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_end] = ACTIONS(68),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(5)] = {
    [sym__line] = STATE(6),
    [sym__statement] = STATE(35),
    [sym_comment] = STATE(35),
    [sym_line_comment] = STATE(26),
    [sym_program_definition] = STATE(35),
    [sym_mata_block] = STATE(35),
    [sym_macro_definition] = STATE(35),
    [sym_command] = STATE(35),
    [sym_prefix] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(70),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(72),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(6)] = {
    [sym__line] = STATE(6),
    [sym__statement] = STATE(35),
    [sym_comment] = STATE(35),
    [sym_line_comment] = STATE(26),
    [sym_program_definition] = STATE(35),
    [sym_mata_block] = STATE(35),
    [sym_macro_definition] = STATE(35),
    [sym_command] = STATE(35),
    [sym_prefix] = STATE(36),
    [aux_sym_source_file_repeat1] = STATE(6),
    [ts_builtin_sym_end] = ACTIONS(74),
    [sym_identifier] = ACTIONS(76),
    [sym__newline] = ACTIONS(79),
    [aux_sym_line_comment_token1] = ACTIONS(82),
    [aux_sym_line_comment_token2] = ACTIONS(85),
    [sym_block_comment] = ACTIONS(88),
    [anon_sym_program] = ACTIONS(91),
    [anon_sym_mata] = ACTIONS(94),
    [anon_sym_local] = ACTIONS(97),
    [anon_sym_loc] = ACTIONS(97),
    [anon_sym_global] = ACTIONS(97),
    [anon_sym_gl] = ACTIONS(97),
    [anon_sym_tempvar] = ACTIONS(100),
    [anon_sym_tempname] = ACTIONS(100),
    [anon_sym_tempfile] = ACTIONS(100),
    [anon_sym_by] = ACTIONS(103),
    [anon_sym_bysort] = ACTIONS(103),
    [anon_sym_bys] = ACTIONS(103),
    [anon_sym_quietly] = ACTIONS(103),
    [anon_sym_qui] = ACTIONS(103),
    [anon_sym_noisily] = ACTIONS(103),
    [anon_sym_noi] = ACTIONS(103),
    [anon_sym_capture] = ACTIONS(103),
    [anon_sym_cap] = ACTIONS(103),
    [anon_sym_sortpreserve] = ACTIONS(103),
    [sym__line_start] = ACTIONS(106),
  },
  [STATE(7)] = {
    [sym__statement] = STATE(32),
    [sym_comment] = STATE(32),
    [sym_line_comment] = STATE(26),
    [sym_program_definition] = STATE(32),
    [sym__program_line] = STATE(2),
    [sym_mata_block] = STATE(32),
    [sym_macro_definition] = STATE(32),
    [sym_command] = STATE(32),
    [sym_prefix] = STATE(36),
    [aux_sym_program_definition_repeat1] = STATE(2),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(109),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_end] = ACTIONS(111),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(8)] = {
    [sym__statement] = STATE(32),
    [sym_comment] = STATE(32),
    [sym_line_comment] = STATE(26),
    [sym_program_definition] = STATE(32),
    [sym__program_line] = STATE(3),
    [sym_mata_block] = STATE(32),
    [sym_macro_definition] = STATE(32),
    [sym_command] = STATE(32),
    [sym_prefix] = STATE(36),
    [aux_sym_program_definition_repeat1] = STATE(3),
    [sym_identifier] = ACTIONS(5),
    [sym__newline] = ACTIONS(27),
    [aux_sym_line_comment_token1] = ACTIONS(9),
    [aux_sym_line_comment_token2] = ACTIONS(11),
    [sym_block_comment] = ACTIONS(13),
    [anon_sym_program] = ACTIONS(15),
    [anon_sym_end] = ACTIONS(113),
    [anon_sym_mata] = ACTIONS(17),
    [anon_sym_local] = ACTIONS(19),
    [anon_sym_loc] = ACTIONS(19),
    [anon_sym_global] = ACTIONS(19),
    [anon_sym_gl] = ACTIONS(19),
    [anon_sym_tempvar] = ACTIONS(21),
    [anon_sym_tempname] = ACTIONS(21),
    [anon_sym_tempfile] = ACTIONS(21),
    [anon_sym_by] = ACTIONS(23),
    [anon_sym_bysort] = ACTIONS(23),
    [anon_sym_bys] = ACTIONS(23),
    [anon_sym_quietly] = ACTIONS(23),
    [anon_sym_qui] = ACTIONS(23),
    [anon_sym_noisily] = ACTIONS(23),
    [anon_sym_noi] = ACTIONS(23),
    [anon_sym_capture] = ACTIONS(23),
    [anon_sym_cap] = ACTIONS(23),
    [anon_sym_sortpreserve] = ACTIONS(23),
    [sym__line_start] = ACTIONS(25),
  },
  [STATE(9)] = {
    [ts_builtin_sym_end] = ACTIONS(115),
    [sym_identifier] = ACTIONS(117),
    [sym__newline] = ACTIONS(115),
    [aux_sym_line_comment_token1] = ACTIONS(115),
    [aux_sym_line_comment_token2] = ACTIONS(117),
    [sym_block_comment] = ACTIONS(115),
    [anon_sym_program] = ACTIONS(117),
    [anon_sym_mata] = ACTIONS(117),
    [anon_sym_local] = ACTIONS(117),
    [anon_sym_loc] = ACTIONS(117),
    [anon_sym_global] = ACTIONS(117),
    [anon_sym_gl] = ACTIONS(117),
    [anon_sym_tempvar] = ACTIONS(117),
    [anon_sym_tempname] = ACTIONS(117),
    [anon_sym_tempfile] = ACTIONS(117),
    [anon_sym_by] = ACTIONS(117),
    [anon_sym_bysort] = ACTIONS(117),
    [anon_sym_bys] = ACTIONS(117),
    [anon_sym_quietly] = ACTIONS(117),
    [anon_sym_qui] = ACTIONS(117),
    [anon_sym_noisily] = ACTIONS(117),
    [anon_sym_noi] = ACTIONS(117),
    [anon_sym_capture] = ACTIONS(117),
    [anon_sym_cap] = ACTIONS(117),
    [anon_sym_sortpreserve] = ACTIONS(117),
    [sym__line_start] = ACTIONS(115),
  },
  [STATE(10)] = {
    [sym_identifier] = ACTIONS(119),
    [sym__newline] = ACTIONS(121),
    [aux_sym_line_comment_token1] = ACTIONS(121),
    [aux_sym_line_comment_token2] = ACTIONS(119),
    [sym_block_comment] = ACTIONS(121),
    [anon_sym_program] = ACTIONS(119),
    [anon_sym_end] = ACTIONS(119),
    [anon_sym_mata] = ACTIONS(119),
    [anon_sym_local] = ACTIONS(119),
    [anon_sym_loc] = ACTIONS(119),
    [anon_sym_global] = ACTIONS(119),
    [anon_sym_gl] = ACTIONS(119),
    [anon_sym_tempvar] = ACTIONS(119),
    [anon_sym_tempname] = ACTIONS(119),
    [anon_sym_tempfile] = ACTIONS(119),
    [anon_sym_by] = ACTIONS(119),
    [anon_sym_bysort] = ACTIONS(119),
    [anon_sym_bys] = ACTIONS(119),
    [anon_sym_quietly] = ACTIONS(119),
    [anon_sym_qui] = ACTIONS(119),
    [anon_sym_noisily] = ACTIONS(119),
    [anon_sym_noi] = ACTIONS(119),
    [anon_sym_capture] = ACTIONS(119),
    [anon_sym_cap] = ACTIONS(119),
    [anon_sym_sortpreserve] = ACTIONS(119),
    [sym__line_start] = ACTIONS(121),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 4,
    ACTIONS(123), 1,
      anon_sym_end,
    ACTIONS(125), 1,
      anon_sym_COLON,
    ACTIONS(127), 1,
      aux_sym__mata_line_token1,
    STATE(13), 2,
      sym__mata_line,
      aux_sym_mata_block_repeat1,
  [14] = 3,
    ACTIONS(127), 1,
      aux_sym__mata_line_token1,
    ACTIONS(129), 1,
      anon_sym_end,
    STATE(15), 2,
      sym__mata_line,
      aux_sym_mata_block_repeat1,
  [25] = 3,
    ACTIONS(127), 1,
      aux_sym__mata_line_token1,
    ACTIONS(129), 1,
      anon_sym_end,
    STATE(14), 2,
      sym__mata_line,
      aux_sym_mata_block_repeat1,
  [36] = 3,
    ACTIONS(131), 1,
      anon_sym_end,
    ACTIONS(133), 1,
      aux_sym__mata_line_token1,
    STATE(14), 2,
      sym__mata_line,
      aux_sym_mata_block_repeat1,
  [47] = 3,
    ACTIONS(127), 1,
      aux_sym__mata_line_token1,
    ACTIONS(136), 1,
      anon_sym_end,
    STATE(14), 2,
      sym__mata_line,
      aux_sym_mata_block_repeat1,
  [58] = 3,
    ACTIONS(138), 1,
      sym_identifier,
    ACTIONS(140), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_macro_definition_repeat1,
  [68] = 3,
    ACTIONS(142), 1,
      sym_identifier,
    ACTIONS(145), 1,
      sym__newline,
    STATE(17), 1,
      aux_sym_macro_definition_repeat1,
  [78] = 2,
    ACTIONS(138), 1,
      sym_identifier,
    STATE(16), 1,
      aux_sym_macro_definition_repeat1,
  [85] = 2,
    ACTIONS(147), 1,
      sym_identifier,
    ACTIONS(149), 1,
      anon_sym_define,
  [92] = 2,
    ACTIONS(151), 1,
      sym__newline,
    ACTIONS(153), 1,
      sym__rest_of_line,
  [99] = 2,
    ACTIONS(155), 1,
      sym__newline,
    ACTIONS(157), 1,
      sym__rest_of_line,
  [106] = 1,
    ACTIONS(159), 2,
      sym__newline,
      sym_identifier,
  [111] = 2,
    ACTIONS(161), 1,
      sym__newline,
    ACTIONS(163), 1,
      sym__rest_of_line,
  [118] = 1,
    ACTIONS(165), 2,
      anon_sym_end,
      aux_sym__mata_line_token1,
  [123] = 1,
    ACTIONS(167), 1,
      sym__newline,
  [127] = 1,
    ACTIONS(169), 1,
      sym__newline,
  [131] = 1,
    ACTIONS(171), 1,
      sym_identifier,
  [135] = 1,
    ACTIONS(173), 1,
      sym__newline,
  [139] = 1,
    ACTIONS(175), 1,
      sym__newline,
  [143] = 1,
    ACTIONS(177), 1,
      ts_builtin_sym_end,
  [147] = 1,
    ACTIONS(179), 1,
      sym__newline,
  [151] = 1,
    ACTIONS(181), 1,
      sym__newline,
  [155] = 1,
    ACTIONS(183), 1,
      sym__newline,
  [159] = 1,
    ACTIONS(185), 1,
      sym__newline,
  [163] = 1,
    ACTIONS(187), 1,
      sym__newline,
  [167] = 1,
    ACTIONS(189), 1,
      sym_identifier,
  [171] = 1,
    ACTIONS(191), 1,
      sym_identifier,
  [175] = 1,
    ACTIONS(193), 1,
      sym__newline,
  [179] = 1,
    ACTIONS(195), 1,
      aux_sym_line_comment_token3,
  [183] = 1,
    ACTIONS(197), 1,
      sym__newline,
  [187] = 1,
    ACTIONS(199), 1,
      sym__newline,
  [191] = 1,
    ACTIONS(201), 1,
      anon_sym_STAR,
  [195] = 1,
    ACTIONS(203), 1,
      sym__newline,
  [199] = 1,
    ACTIONS(205), 1,
      sym__newline,
  [203] = 1,
    ACTIONS(207), 1,
      sym_identifier,
  [207] = 1,
    ACTIONS(209), 1,
      sym__newline,
  [211] = 1,
    ACTIONS(211), 1,
      sym__newline,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(11)] = 0,
  [SMALL_STATE(12)] = 14,
  [SMALL_STATE(13)] = 25,
  [SMALL_STATE(14)] = 36,
  [SMALL_STATE(15)] = 47,
  [SMALL_STATE(16)] = 58,
  [SMALL_STATE(17)] = 68,
  [SMALL_STATE(18)] = 78,
  [SMALL_STATE(19)] = 85,
  [SMALL_STATE(20)] = 92,
  [SMALL_STATE(21)] = 99,
  [SMALL_STATE(22)] = 106,
  [SMALL_STATE(23)] = 111,
  [SMALL_STATE(24)] = 118,
  [SMALL_STATE(25)] = 123,
  [SMALL_STATE(26)] = 127,
  [SMALL_STATE(27)] = 131,
  [SMALL_STATE(28)] = 135,
  [SMALL_STATE(29)] = 139,
  [SMALL_STATE(30)] = 143,
  [SMALL_STATE(31)] = 147,
  [SMALL_STATE(32)] = 151,
  [SMALL_STATE(33)] = 155,
  [SMALL_STATE(34)] = 159,
  [SMALL_STATE(35)] = 163,
  [SMALL_STATE(36)] = 167,
  [SMALL_STATE(37)] = 171,
  [SMALL_STATE(38)] = 175,
  [SMALL_STATE(39)] = 179,
  [SMALL_STATE(40)] = 183,
  [SMALL_STATE(41)] = 187,
  [SMALL_STATE(42)] = 191,
  [SMALL_STATE(43)] = 195,
  [SMALL_STATE(44)] = 199,
  [SMALL_STATE(45)] = 203,
  [SMALL_STATE(46)] = 207,
  [SMALL_STATE(47)] = 211,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = false}}, SHIFT(20),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(5),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [11] = {.entry = {.count = 1, .reusable = false}}, SHIFT(38),
  [13] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [15] = {.entry = {.count = 1, .reusable = false}}, SHIFT(19),
  [17] = {.entry = {.count = 1, .reusable = false}}, SHIFT(11),
  [19] = {.entry = {.count = 1, .reusable = false}}, SHIFT(27),
  [21] = {.entry = {.count = 1, .reusable = false}}, SHIFT(18),
  [23] = {.entry = {.count = 1, .reusable = false}}, SHIFT(37),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(3),
  [29] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [31] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [34] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(3),
  [37] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [40] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [43] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [46] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [49] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0),
  [51] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [54] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [57] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [60] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [63] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_program_definition_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [68] = {.entry = {.count = 1, .reusable = false}}, SHIFT(31),
  [70] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_source_file, 1, 0, 0),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [74] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0),
  [76] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(20),
  [79] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(6),
  [82] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [85] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(38),
  [88] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [91] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(19),
  [94] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(11),
  [97] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(27),
  [100] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(18),
  [103] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(37),
  [106] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_source_file_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [109] = {.entry = {.count = 1, .reusable = true}}, SHIFT(2),
  [111] = {.entry = {.count = 1, .reusable = false}}, SHIFT(41),
  [113] = {.entry = {.count = 1, .reusable = false}}, SHIFT(44),
  [115] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__line, 2, 0, 0),
  [117] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__line, 2, 0, 0),
  [119] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__program_line, 2, 0, 0),
  [121] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__program_line, 2, 0, 0),
  [123] = {.entry = {.count = 1, .reusable = false}}, SHIFT(28),
  [125] = {.entry = {.count = 1, .reusable = false}}, SHIFT(12),
  [127] = {.entry = {.count = 1, .reusable = false}}, SHIFT(33),
  [129] = {.entry = {.count = 1, .reusable = false}}, SHIFT(34),
  [131] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_mata_block_repeat1, 2, 0, 0),
  [133] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_mata_block_repeat1, 2, 0, 0), SHIFT_REPEAT(33),
  [136] = {.entry = {.count = 1, .reusable = false}}, SHIFT(46),
  [138] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 2, 0, 3),
  [142] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_macro_definition_repeat1, 2, 0, 4), SHIFT_REPEAT(22),
  [145] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_definition_repeat1, 2, 0, 4),
  [147] = {.entry = {.count = 1, .reusable = false}}, SHIFT(4),
  [149] = {.entry = {.count = 1, .reusable = false}}, SHIFT(45),
  [151] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 1, 0, 1),
  [153] = {.entry = {.count = 1, .reusable = false}}, SHIFT(43),
  [155] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_macro_definition, 2, 0, 2),
  [157] = {.entry = {.count = 1, .reusable = false}}, SHIFT(25),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_macro_definition_repeat1, 1, 0, 1),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_command, 2, 0, 2),
  [163] = {.entry = {.count = 1, .reusable = false}}, SHIFT(40),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__mata_line, 2, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_macro_definition, 3, 0, 2),
  [169] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_comment, 1, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [173] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mata_block, 2, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 3, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 3, 0, 2),
  [181] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [183] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [185] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mata_block, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [189] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_prefix, 1, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_line_comment, 1, 0, 0),
  [195] = {.entry = {.count = 1, .reusable = true}}, SHIFT(29),
  [197] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 3, 0, 2),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 4, 0, 5),
  [201] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_command, 2, 0, 1),
  [205] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 4, 0, 2),
  [207] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [209] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_mata_block, 4, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_program_definition, 5, 0, 5),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__line_start = 0,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__line_start] = sym__line_start,
};

static const bool ts_external_scanner_states[2][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__line_start] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_stata_external_scanner_create(void);
void tree_sitter_stata_external_scanner_destroy(void *);
bool tree_sitter_stata_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_stata_external_scanner_serialize(void *, char *);
void tree_sitter_stata_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_stata(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .field_names = ts_field_names,
    .field_map_slices = ts_field_map_slices,
    .field_map_entries = ts_field_map_entries,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .keyword_lex_fn = ts_lex_keywords,
    .keyword_capture_token = sym_identifier,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_stata_external_scanner_create,
      tree_sitter_stata_external_scanner_destroy,
      tree_sitter_stata_external_scanner_scan,
      tree_sitter_stata_external_scanner_serialize,
      tree_sitter_stata_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "stata",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 0,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
